repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
        args: ["custom_components/city_visitor_parking"]
        files: ^custom_components/city_visitor_parking/.*\.py$
  - repo: local
    hooks:
      - id: hassfest
        name: hassfest (city_visitor_parking)
        entry: python
        args:
          - -m
          - script.hassfest
          - --action
          - validate
          - --core-path
          - ../homeassistant-core
          - --integration-path
          - custom_components/city_visitor_parking
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
      - id: frontend-types
        name: frontend types
        entry: yarn --cwd custom_components/city_visitor_parking/frontend lint:types
        language: system
        files: ^custom_components/city_visitor_parking/frontend/.*\.(ts|json)$
        pass_filenames: false
