repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: hassfest
        name: hassfest (city_visitor_parking)
        entry: python
        args:
          - -m
          - script.hassfest
          - --action
          - validate
          - --core-path
          - ../homeassistant-core
          - --integration-path
          - custom_components/city_visitor_parking
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
      - id: frontend-eslint
        name: frontend eslint
        entry: yarn --cwd custom_components/city_visitor_parking/frontend lint:eslint
        language: system
        files: ^custom_components/city_visitor_parking/frontend/src/.*\.ts$
        pass_filenames: false
      - id: frontend-prettier
        name: frontend prettier
        entry: yarn --cwd custom_components/city_visitor_parking/frontend lint:prettier --write
        language: system
        files: ^custom_components/city_visitor_parking/frontend/src/.*\.(ts|json|md|css)$
        pass_filenames: false
      - id: frontend-types
        name: frontend types
        entry: yarn --cwd custom_components/city_visitor_parking/frontend lint:types
        language: system
        files: ^custom_components/city_visitor_parking/frontend/.*\.(ts|json)$
        pass_filenames: false
      - id: frontend-test
        name: frontend test
        entry: yarn --cwd custom_components/city_visitor_parking/frontend test
        language: system
        files: ^custom_components/city_visitor_parking/frontend/.*\.(ts|json|md|css)$
        pass_filenames: false
      - id: frontend-build
        name: frontend build
        entry: yarn --cwd custom_components/city_visitor_parking/frontend build
        language: system
        files: ^custom_components/city_visitor_parking/frontend/.*\.(ts|json|md|css)$
        pass_filenames: false
